# Generated by Django 5.1.7 on 2026-05-01 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailterms', '0002_wagtailtermtag_term_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['term']},
        ),
    ]
